version: '2.1'

services:
  master:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_master"
    image: 'citusdata/citus:9.2.2'
    ports: ["${MASTER_EXTERNAL_PORT:-5433}:5432"]
    labels: ['com.citusdata.role=Master']
    environment:
        - POSTGRES_PASSWORD=""
        - POSTGRES_HOST_AUTH_METHOD=trust
  worker:
    image: 'citusdata/citus:9.2.2'
    labels: ['com.citusdata.role=Worker']
    environment:
        - POSTGRES_PASSWORD=""
        - POSTGRES_HOST_AUTH_METHOD=trust
    depends_on: { manager: { condition: service_healthy } }
  manager:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_manager"
    image: 'citusdata/membership-manager:0.2.0'
    volumes: ['/var/run/docker.sock:/var/run/docker.sock']
    depends_on: { master: { condition: service_healthy } }
